accelerate launch \
--mixed_precision=bf16 \
-m lerobot.scripts.lerobot_value_train  \
--value.type=pistar06 \
--value.backbone_source=pi05 \
--value.freeze_language_model=true \
--value.freeze_vision_encoder=true \
--targets.length_scale_quantile=0.9 \
--batch_size=8 --steps=50000 \
--save_freq=2000 \
--save_checkpoint=true  \
--wandb.enable=true  \
--wandb.disable_artifact=true  \
--job_name=value_socks6000_freeze \
--dataset.repo_id=noetix/socks6000  \
--dataset.root=/mnt/data2/datasets/lerobot_socks_sft3000_auto1300_vr800/  \
--output_dir=outputs/value_train/value_socks6000_freeze \
